version: "3.3"

services:
  traefik:
    image: "traefik:v3.2"
    container_name: "whitemanedhorses-traefik-traefik"
    networks:
      - default
      - whitemanedhorses
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=aladina.kate@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "whitemanedhorses-traefik-whoami"
    networks:
      - whitemanedhorses
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`app1.whitemanedhorses.ru`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"

networks:
  whitemanedhorses:
    name: whitemanedhorses
    external: true
