---
services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: "whitemanedhorses-authentik-postgresql"
    restart: unless-stopped
    networks:
      - authentik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env

  redis:
    image: docker.io/library/redis:alpine
    container_name: "whitemanedhorses-authentik-redis"
    restart: unless-stopped
    command: --save 60 1 --loglevel warning
    networks:
      - authentik
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.0}
    container_name: "whitemanedhorses-authentik-server"
    restart: unless-stopped
    networks:
      - authentik
      - whitemanedhorses
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: whitemanedhorses-authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: whitemanedhorses-authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=whitemanedhorses"
      - "traefik.http.routers.authentik.rule=Host(`auth.whitemanedhorses.ru`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    # ports:
    # - "${COMPOSE_PORT_HTTP:-9000}:9000"
    # - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.12.0}
    restart: unless-stopped
    networks:
      - authentik
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: whitemanedhorses-authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: whitemanedhorses-authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
    driver: local
  redis:
    driver: local

networks:
  authentik:
    name: authentik
    external: false
  whitemanedhorses:
    name: whitemanedhorses
    external: true
